{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .containerName }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .containerName }}
          image: {{ .image }}:{{ .tag }}
          ports:
            - containerPort: {{ .port }}
---
{{- end }}
