{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .containerName }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  type: NodePort
---
{{- end }}
